CONN_STRING_REMOTE = '***'

CONN_STRING_LOCAL = '***'


PERMISSION_ADMIN = 0
PERMISSION_USER = 16

FILM_TYPE = 0
MOVIE_SERIES_TYPE = 1

PORTAL_NEWS_TYPE = 0
CINEMA_NEWS_TYPE = 1
ARTICLES_TYPE = 2

MAX_LINES_IN_TOP_RATING_LIST = 10
MAX_LINES_IN_RATING_PAGE = 10
MAX_FILMS_PER_PAGE = 4
MAX_LINES_IN_NEWS_FEED = 20

ICON_PATH = 'img/'
UPLOADS_PATH = "uploads/"


LOCAL_URI_REDIRECT = 'http://localhost:5000/facebook_login'
REMOTE_URI_REDIRECT = 'https://nesk-kino.herokuapp.com/facebook_login'
